[platformio]
default_envs = matrix

[env:matrix]
platform   = espressif32@6.7.0
board      = esp32-s3-devkitc-1   ; 通用 ESP32-S3；Waveshare 暂无专用 board id
board_build.flash_size = 4MB
framework  = arduino
monitor_speed = 115200
upload_speed  = 921600

build_flags =
  -D MATRIX_PIN=14                 ; 8x8 WS2812 矩阵数据脚 (PIN_NEOPIXEL)
  -D MATRIX_W=8
  -D MATRIX_H=8
  -D LED_BUILTIN=14
  ; Adafruit_NeoPixel 库通过 lib_deps 引入
lib_deps =
  adafruit/Adafruit NeoPixel @ ^1.12.0
