[platformio]
default_envs = timercam-cam

[env:timercam-cam]
platform   = espressif32@6.7.0
board      = m5stack-timer-cam
framework  = arduino
monitor_speed = 115200
upload_speed  = 921600

build_flags =
  -DBOARD_HAS_PSRAM                ; TimerCam F 板载 8MB PSRAM，摄像头帧缓冲要用

; esp32-camera 驱动（含 OV3660 支持）
lib_deps =
  esp32-camera @ ^2.0.0
