[platformio]
default_envs = timercam

[env:timercam]
platform   = espressif32@6.7.0
board      = m5stack-timer-cam       ; PlatformIO 内置的 Timer Camera board id
framework  = arduino
monitor_speed = 115200
upload_speed  = 921600

build_flags =
  -D LED_PIN=2                     ; 板载状态 LED
