[platformio]
default_envs = esp32-s3-ai-board

[env:esp32-s3-ai-board]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DENABLE_LCD_TEST=1
  -DENABLE_RGB_TEST=1
  -DENABLE_MIC_TEST=1
  -DENABLE_SPEAKER_TEST=1

lib_deps =
  adafruit/Adafruit GFX Library @ ^1.11.11
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
  adafruit/Adafruit NeoPixel @ ^1.12.3
