[platformio]
default_envs = matrix

[env:matrix]
platform   = espressif32@6.7.0
board      = esp32-s3-devkitc-1
board_build.flash_size = 4MB
framework  = arduino
monitor_speed = 115200
upload_speed  = 921600

build_flags =
  -D I2C_SDA=11        ; QMI8658 SDA（原理图核实，未引出排针）
  -D I2C_SCL=12        ; QMI8658 SCL
