[platformio]
default_envs = stickc-plus2

[env:stickc-plus2]
platform   = espressif32@6.7.0
board      = m5stick-c            ; M5StickC（与 Plus/Plus2 引脚兼容）
framework  = arduino
monitor_speed = 115200
upload_speed  = 921600

build_flags =
  -D LED_PIN=10                   ; 板载红色 LED
